
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hi
 */
public class DOCTORFORM extends javax.swing.JFrame {

    /**
     * Creates new form DOCTORFORM
     */
    public DOCTORFORM() {
        initComponents();
        
        try 
        {
          FileInputStream ob = new FileInputStream("DOC_ID.txt");
          StringBuilder sb = new StringBuilder();
          int i;
         while ((i = ob.read()) != -1) 
         {
             sb.append((char) i);
         }
         ob.close();
         String s = sb.toString().trim();
         int auto_id = Integer.parseInt(s);
         auto_id++;
         
         FileOutputStream ob2 = new FileOutputStream("DOC_ID.txt");
         String h = String.valueOf(auto_id);
         ob2.write(h.getBytes());
         ob2.close();

         jTextField1.setText("D0" + h);
         jTextField1.requestFocus();

        } 
        catch (Exception e) 
        { 
            JOptionPane.showMessageDialog(this, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("DOCTOR DETAILS FORM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(630, 20, 610, 60);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("DOCTOR ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 170, 310, 50);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("DOCTOR NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 260, 310, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("SPECIALIZATION");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 360, 310, 50);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("AVAILABLE DAYS & TIME");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 460, 310, 50);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("CONTACT NUMBER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 560, 310, 50);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(700, 180, 480, 50);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Emergency Medicine Specialist", "Cardiologist", "Neurologist", "Gynecologist", "Pulmonologist", "Nephrologist", "Pediatrician", "Dermatologist", "Psychiatrist" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(700, 360, 480, 50);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MONDAY / 10AM-3AM", "TUESDAY / 10.30AM-6PM", "WEDNESDAY / 11AM-5PM", "THURSDAY / 10AM-4PM", "FRIDAY / 12PM-7PM", "SATURDAY / 11AM-5PM", "SUNDAY / 10AM-12.30PM" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(700, 460, 480, 50);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(700, 570, 480, 50);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("DOCTOR ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1250, 180, 180, 40);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(1460, 180, 420, 50);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1460, 260, 420, 240);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("READ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1230, 270, 210, 50);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1230, 360, 210, 50);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1230, 450, 210, 50);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setText("SUBMIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(770, 690, 220, 60);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1150, 690, 220, 60);

        jComboBox3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dr. Arjun (Emergency Medicine Specialist)", "Dr. Riya ( Cardiologist)", "Dr. Raghav Kumar ( Neurologist)", "Dr. Sneha ( Gynecologist)", "Dr. Karthik ( Pulmonologist)", "Dr. Divya ( Nephrologist)", "Dr. Aditya Sharma ( Pediatrician) ", "Dr. Nisha ( Dermatologist)", "Dr. Rohit ( Psychiatrist)" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(700, 270, 480, 50);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 20, 170, 180);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setText("CLICK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(100, 230, 91, 31);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatGPT Image Nov 21, 2025, 02_19_51 PM.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1530, -70, 1530, 1180);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatGPT Image Nov 21, 2025, 02_19_51 PM.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, -80, 1530, 1180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jComboBox2.requestFocus();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        jTextField3.requestFocus();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try 
{
    Connection con = null;
    Statement st = null;

    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
    con = DriverManager.getConnection("jdbc:odbc:sampleDSN", "", "");
    st = con.createStatement();

    String doctorId = jTextField4.getText().trim();
    String sql = "SELECT * FROM DOC_FORM WHERE doctorid = '" + doctorId + "'";
    ResultSet rs = st.executeQuery(sql);

    String DOCTORID = "", DOCTORNAME = "", SPECIALIZATION = "", AVAILABLEDAYSTIME = "", CONTACTNUMBER = "";
    int found = 0;

    while (rs.next()) 
    {
        DOCTORID = rs.getString("doctorid");
        DOCTORNAME = rs.getString("doctorname");
        SPECIALIZATION = rs.getString("specialization");
        AVAILABLEDAYSTIME = rs.getString("availabledays");
        CONTACTNUMBER = rs.getString("contactnumber");
        found = 1;
    }

    if (found == 0) 
    {
        JOptionPane.showMessageDialog(this, "No Data Found");
        return;
    }

    // ---- FILL FIELDS ----
    jTextField1.setText(DOCTORID);
    jComboBox3.setSelectedItem(DOCTORNAME);
    jComboBox1.setSelectedItem(SPECIALIZATION);
    jComboBox2.setSelectedItem(AVAILABLEDAYSTIME);
    jTextField3.setText(CONTACTNUMBER);

    jTextArea1.setText(
            "DOCTORID: " + DOCTORID +
            "\nDOCTORNAME: " + DOCTORNAME +
            "\nSPECIALIZATION: " + SPECIALIZATION +
            "\nCONTACTNUMBER: " + CONTACTNUMBER
    );

    st.close();
    con.close();
}
catch (Exception e) 
{
    JOptionPane.showMessageDialog(this, e.getMessage());
}

// ----------------------- IMAGE LOADING SECTION -----------------------

String doctorId = jTextField4.getText().trim();
File folder = new File("DOC_PIC");

if (!folder.exists()) 
{
    folder.mkdirs();
}

jLabel8.setIcon(null);  // CLEAR OLD IMAGE

// Supported extensions
String[] extList = {"jpg", "jpeg", "png", "gif"};
File foundImage = null;

for (String ext : extList) 
{
    File temp = new File(folder, doctorId + "." + ext);
    if (temp.exists()) 
    {
        foundImage = temp;
        break;
    }
}

// ---- CASE 1: IMAGE FOUND —> SHOW IT ----
if (foundImage != null) 
{
    ImageIcon icon = new ImageIcon(foundImage.getAbsolutePath());
    Image img = icon.getImage().getScaledInstance(
        jLabel8.getWidth(), 
        jLabel8.getHeight(), 
        Image.SCALE_SMOOTH
    );
    jLabel8.setIcon(new ImageIcon(img));
}
// ---- CASE 2: IMAGE NOT FOUND —> ASK USER TO UPLOAD ----
else 
{
    JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Upload Image for ID: " + doctorId);
    chooser.addChoosableFileFilter(
        new javax.swing.filechooser.FileNameExtensionFilter("Image Files", extList)
    );
    chooser.setAcceptAllFileFilterUsed(false);

    int choose = chooser.showOpenDialog(this);

    if (choose == JFileChooser.APPROVE_OPTION) 
    {
        File selected = chooser.getSelectedFile();
        String ext = selected.getName().substring(selected.getName().lastIndexOf('.') + 1).toLowerCase();

        File saveTo = new File(folder, doctorId + "." + ext);

        try 
        {
            java.nio.file.Files.copy(
                selected.toPath(), 
                saveTo.toPath(),
                java.nio.file.StandardCopyOption.REPLACE_EXISTING
            );

            ImageIcon icon = new ImageIcon(saveTo.getAbsolutePath());
            Image img = icon.getImage().getScaledInstance(
                jLabel8.getWidth(), 
                jLabel8.getHeight(), 
                Image.SCALE_SMOOTH
            );
            jLabel8.setIcon(new ImageIcon(img));

            JOptionPane.showMessageDialog(this, "Image Saved Successfully!");
        }
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        jComboBox3.requestFocus();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
               String s = jTextField3.getText();
           if (s.matches("[6-9][0-9]{9}"))
           {
               System.out.println("Valid number..!");
           }
           else
           {
               JOptionPane.showMessageDialog(this, "Invalid phone number!");
               jTextField3.setText("");
               jTextField3.requestFocus();
           }
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        jTextField3.requestFocus();
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            
         try
        {
            Connection con=null;
            Statement st=null;
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con=DriverManager.getConnection("jdbc:odbc:sampleDSN","","");
            st=con.createStatement();
            String ss="insert into DOC_FORM values('"+jTextField1.getText()+"','"+(String)jComboBox3.getSelectedItem()+"','"+(String)jComboBox1.getSelectedItem()+"','"+(String)jComboBox2.getSelectedItem()+"','"+jTextField3.getText()+"')";
            st.executeUpdate(ss);
            JOptionPane.showMessageDialog(this,"Saved..!");
            con.close();
            st.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Connection con=null;
            Statement st=null;
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con=DriverManager.getConnection("jdbc:odbc:sampleDSN","","");
            st=con.createStatement();
            //UPDATE QUERY:
            String s="delete from DOC_FORM where doctorid=('"+jTextField4.getText()+"')";
            st.executeUpdate(s);
            String ss="insert into DOC_FORM values('"+jTextField1.getText()+"','"+(String)jComboBox3.getSelectedItem()+"','"+(String)jComboBox1.getSelectedItem()+"','"+(String)jComboBox2.getSelectedItem()+"','"+jTextField3.getText()+"')";
            st.executeUpdate(ss);
            JOptionPane.showMessageDialog(this,jTextField1.getText()+" Details are Updated...!");
            con.close();
            st.close() ;
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection con=null;
            Statement st=null;
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con=DriverManager.getConnection("jdbc:odbc:sampleDSN","","");
            st=con.createStatement();
            String s="delete from DOC_FORM where doctorid=('"+jTextField1.getText()+"')";
            st.executeUpdate(s);
            JOptionPane.showMessageDialog(this,"deleted...!");

            con.close();
            st.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Select Employee Image");
    
    // Allow only image files
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif");
    fileChooser.setFileFilter(filter);

    int result = fileChooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) 
    {
        File selectedFile = fileChooser.getSelectedFile();

        try 
        {
            // Display image in JLabel
            ImageIcon icon = new ImageIcon(selectedFile.getAbsolutePath());
            Image img = icon.getImage().getScaledInstance(jLabel8.getWidth(), jLabel8.getHeight(), Image.SCALE_SMOOTH);
            jLabel8.setIcon(new ImageIcon(img));

            // Create destination folder if not exists
            File destFolder = new File("DOC_PIC");
            if (!destFolder.exists()) {
                destFolder.mkdirs();
        }

            // Save the image to "saved_images" folder
           // String fileName = selectedFile.getName();
            String fileName = jTextField1.getText();
            File destination = new File(destFolder, fileName);

            // Copy the file
            Files.copy(selectedFile.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);

            JOptionPane.showMessageDialog(this, "Image saved to: " + destination.getAbsolutePath());

        } 
        catch (IOException e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving image: " + e.getMessage());
        }
    }


 

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DOCTORFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DOCTORFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DOCTORFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DOCTORFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DOCTORFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
